config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  
  root to: 'homepage#index', as: :month
  get "homepage/week",to: "homepage#week", as: :week

  get "/habits", to: "habit#index", as: :habits
  post "/habits", to: "habit#create", as: :create
  post "/answer", to: "habit#answer", as: :answer
  get "/habits/edit/:id", to: "habit#edit", as: :edit
  get "/habits/export", to: "habit#export", as: :export
  patch "/habits/edit/:id", to: "habit#update", as: :update
  delete "/:id/delete", to: "habit#delete", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  has_many :habit_confirmations

  def confirmed_today?
    habit_confirmations.where(confirmation_date: Date.today).any?
  end

  def answer(date = Date.today)
    habit_confirmations.find_by(confirmation_date: date).answer
  end

  def diamonds
    self.habit_confirmations.where(answer: 1)
  end

  def stones
    self.habit_confirmations.where(answer: 0)
  end

  def month(d)
    days_in_month = d.beginning_of_month..d.end_of_month
    self.habit_confirmations.where(confirmation_date: days_in_month, answer: 1).count
  end
end

app/models/habit_confirmation.rb
class HabitConfirmation < ApplicationRecord
  belongs_to :habit
  validates :confirmation_date, presence: true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habit_controller.rb
class HabitController < ApplicationController
  
  def index
    @habits = Habit.all.order(name: :asc)
    @habit = Habit.new
  end

  def export
  end

  def answer
    @habit_confirmation = HabitConfirmation.new(habit_confirmation_params)
    @habit_confirmation.confirmation_date = Date.today
    @habit_confirmation.save!
    redirect_to habits_path
  end

  def create
    @habit = Habit.new(habit_params)

    if @habit.save
      redirect_to habits_path, notice: "#{@habit.name} successfuly created"
    else
      render "new", alert: "#{@habit.name} already exist"
    end
  end

  def edit
    @habit = Habit.find(params[:id])
  end

  def update
    @habit = Habit.find(params[:id])
    if @habit.update(habit_params)
      redirect_to habits_path, notice: 'Habit succesfully edited'
    else
      render :edit
    end
  end

  def delete
    @habit = Habit.find(params[:id])
    @habit.destroy
    redirect_to habits_path, notice: "#{@habit.name} deleted"
  end

  private

  def habit_params
    params.require(:habit).permit(:name)
  end

  def habit_confirmation_params
    params.require(:habit_confirmation_answer).permit(:habit_id, :answer)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    @meetings = Meeting.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def week
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all.order(start_time: :asc)
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "Event was successfully created" }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "Event was updated" }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "Event was destroyed" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_month
    I18n.t("date.month_names")[Date.today.month] + " " + Date.today.strftime("%Y")
  end

  def last_6_months
    (Date.today.beginning_of_month - 5.months..Date.today.beginning_of_month).select do |date|
        date == date.beginning_of_month
      end
  end

  def last_4_months
    (Date.today.beginning_of_month - 3.months..Date.today.beginning_of_month).select do |date|
        date == date.beginning_of_month
      end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/habit/_form.html.haml
= form_with model: @habit, url: url do |f|
  - if @habit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@habit.errors.count, "error")} prohibited this habit from being saved:"
      %ul
        - @habit.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  %button.btn.btn-info{:type => "submit"} Save

app/views/habit/edit.html.haml
= render 'meetings/nav'

.event Edit habit: #{@habit.name}

-# = render partial: 'form', locals: {url: update_path(@habit)}
= render 'form', url: update_path(@habit)

app/views/habit/export.html.haml
- data = {}
- data[:habit_confirmations] = HabitConfirmation.all
- data[:habits] = Habit.all
- data[:meetings] = Meeting.all
= data.to_json

app/views/habit/index.html.haml
= render 'meetings/nav'

.event 
  Add your healthy habbits and track them!
-# .event 
-#   goal_archieved &nbsp; ? &nbsp; become 💎 &nbsp; : &nbsp; lose 2 💎 become ⚠️

.collabsible-close
  %button.btn.btn-info.titel-font.open Check list
  .show
    %table.table.desktop
      %thead
        %tr
          %th.w50 Habit
          %th Done?
          %th.right.w20 Points
      %tbody    
        - @habits.each do |habit|
          %tr
            %td= habit.name 

            - if habit.confirmed_today?
              %td 
                - if habit.answer
                  %button.btn.btn-info Yes!
                - else 
                  %button.btn.btn-info No

            - else
              %td.flex
                = form_with(url:answer_path, method: :post, scope: :habit_confirmation_answer) do |f|
                  = f.hidden_field :habit_id, value: habit.id
                  = f.hidden_field :answer, value: 1
                  %button.btn.btn-dark.marg-r1{:type => "submit"} Yes!

                
                = form_with(url:answer_path, method: :post, scope: :habit_confirmation_answer) do |f|
                  = f.hidden_field :habit_id, value: habit.id
                  = f.hidden_field :answer, value: 0
                  %button.btn.btn-dark{:type => "submit"} No
            
            %td.left.desktop
              - if habit.diamonds.count > 0
                = habit.diamonds.count
                💎
              -# - else
              -#   - habit.diamonds.count * 0
              -#   0 💎
              - if habit.stones.count > 0
                = habit.stones.count
                ⚠️

            %td.left.mobile
              - if habit.diamonds.count > 0
                .div
                  = habit.diamonds.count
                  💎
              - if habit.stones.count > 0
                .div
                  = habit.stones.count
                  ⚠️

.collabsible
  %button.btn.btn-info.titel-font.open Add habbit
  .show
    = render partial: 'form', locals: {url: create_path}

-# %ul
-#   %li August
-#   - @habits.each do |habit|
-#     - for i in 1..12 do
-#       = habit.name
-#       = habit.month(i)
-#       💎

    
.collabsible
  %button.btn.btn-info.titel-font.open Statistics
  .show
    %table.table.table-responsive
      %thead.desctop 
        %tr
          %th Habit
          - last_6_months.each do |i|
            %th= i.strftime("%m %Y")
      %tbody.desctop  
        - @habits.each do |habit|  
          %tr
            %td= habit.name 
            - last_6_months.each do |i|
              %td
                - if habit.month(i) > 0
                  = habit.month(i)
                  💎
    
      %thead.mobile 
        %tr
          %th Habit
          - last_4_months.each do |i|
            %th= i.strftime("%m %Y")
      %tbody.mobile 
        - @habits.each do |habit|  
          %tr
            %td= habit.name 
            - last_4_months.each do |i|
              %td
                - if habit.month(i) > 0
                  = habit.month(i)
                  💎

.collabsible
  %button.btn.btn-info.titel-font.open Settings
  .show
    %table.table
      %thead
        %tr
          %th Name
          %th{:colspan => "2"} Settings

      %tbody
        - @habits.each do |habit|
          %tr
            %td= habit.name
            %td.link= link_to 'Edit', edit_path(habit)
            %td.link= link_to 'x', delete_path(habit), method: :delete, data: { confirm: 'Are you sure?' }

app/views/homepage/index.html.haml
= month_calendar events: @meetings do |date, meetings|
  = date.strftime("%d") 

  - meetings.each do |meeting|
    .event
      = link_to meeting.name, edit_meeting_path(meeting)

app/views/homepage/week.html.haml
= week_calendar number_of_weeks: 2 do |date|
  = date.strftime("%d")

-# = calendar number_of_days: 7 do |date|
-#   = date.strftime("%d")

= link_to "Meetings", meetings_path

app/views/layouts/_header.html.haml
.header 
  %a{:href => "/"} Calendar

.slogan
  ✧ Find positive in every day! ✧

- if flash[:notice].present?
  .alert.info{role: "alert"}
    = sanitize flash[:notice], tags: %w(br ul li strong)

- if flash[:alert].present?
  .alert.alert-danger{role: "alert"}
    = sanitize flash[:alert], tags: %w(br ul li strong)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Calendar
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", :integrity => "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com", :rel => "preconnect"}/
    %link{:crossorigin => "", :href => "https://fonts.gstatic.com", :rel => "preconnect"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Caveat&family=Fredericka+the+Great&family=Quicksand&display=swap", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons", :rel => "stylesheet"}/


    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"}
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  
  %body
    %main.container
      = render "layouts/header"
      %article
        = yield
    -# = render "layouts/footer"

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :start_time
    = f.datetime_select :start_time

  %button.btn.btn-info{:type => "submit"} Save

app/views/meetings/_nav.html.haml
.simple-calendar
  .calendar-heading
    %ul.nav.flex
      %li.nav-item
        <<
        %span.calendar-title
          = link_to current_month, month_path
        >>
      %li.nav-item.end.dropdown
        %span.calendar-title
          = link_to "Habits", habits_path, class: "marg-r"
      %li.nav-item.dropdown
        %span.calendar-title
          = link_to "Add event", new_meeting_path, class: "marg-r"
      %li.nav-item.dropdown
        %span.calendar-title
          = link_to "All events", meetings_path

      %li.nav-item.brgr-r
        .wrapper
          #nav-icon3{:onclick => "this.classList.toggle('show-menu')"}
            %span
            %span
            %span
            %span
          %ul.site-nav-list
            %li
              %span.calendar-title
                = link_to "Habits", habits_path
            %li
              %span.calendar-title
                = link_to "Add event", new_meeting_path
            %li
              %span.calendar-title
                = link_to "All events", meetings_path

app/views/meetings/edit.html.haml
= render 'nav'

.event Editing event: #{@meeting.name}

= render 'form'

= link_to 'Show', @meeting

app/views/meetings/index.html.haml
= render 'nav'

%table.table.table-responsive
  %thead
    %tr
      %th Name
      %th Starts at
      %th{:colspan => "2"} Settings

  %tbody
    - @meetings.each do |meeting|
      %tr
        %td.link= link_to meeting.name, meeting
        %td= meeting.start_time.strftime("%d.%m.%Y %H:%M")
        %td.link= link_to 'Edit', edit_meeting_path(meeting)
        %td.link= link_to 'x', meeting, method: :delete, data: { confirm: 'Are you sure?' }

app/views/meetings/new.html.haml
= render 'nav'

= render 'form'

app/views/meetings/show.html.haml
= render 'nav'
%p
  %b Name:
  = @meeting.name
%p
  %b Starts at:
  = @meeting.start_time

= link_to 'Edit', edit_meeting_path(@meeting)

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title.font
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped.table-responsive
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    %ul.nav.flex
      %li.nav-item
        = link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view
        %span.calendar-title
          = t('date.month_names')[start_date.month]
          = start_date.year
        = link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view, class: "marg-r"
      %li.nav-item.end.dropdown
        %span.calendar-title
          = link_to "Habits", habits_path, class: "marg-r"
      %li.nav-item.dropdown
        %span.calendar-title
          = link_to "Add event", new_meeting_path, class: "marg-r"
      %li.nav-item.dropdown
        %span.calendar-title
          = link_to "All events", meetings_path

      -#My dropdown
      %li.nav-item.brgr-r
        .wrapper
          -# %button.btn{:onclick => "this.classList.toggle('show-menu')"}
          -#   .burger 
          -#   .burger
          -#   .burger
          #nav-icon3{:onclick => "this.classList.toggle('show-menu')"}
            %span
            %span
            %span
            %span
          %ul.site-nav-list
            %li
              %span.calendar-title
                = link_to "Habits", habits_path
            %li
              %span.calendar-title
                = link_to "Add event", new_meeting_path
            %li
              %span.calendar-title
                = link_to "All events", meetings_path

  %table.table.table-striped.table-responsive
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    %ul.nav
      %li.nav-item
        %span.calendar-title
          = link_to t('date.month_names')[start_date.month], month_path, class: "marg-r"
      %li.nav-item
        = link_to t('simple_calendar.previous', default: '<<'), calendar.url_for_previous_view
        - if calendar.number_of_weeks == 1
          %span.calendar-title
            = t('simple_calendar.week', default: 'Week')
            = calendar.week_number
        - else
          %span.calendar-title
            = t('simple_calendar.week', default: 'Week')
            = calendar.week_number
            \- #{calendar.end_week}
        = link_to t('simple_calendar.next', default: '>>'), calendar.url_for_next_view

  %table.table.table-striped.table-responsive
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])